[app]
env = "dev"
http_addr = "0.0.0.0:8080"

[database]
hostname = "127.0.0.1"
port = 3306
name = "planet"
username = "root"
password = "planet"

[swapi]
hostname = "https://swapi.dev"
timeout = "5s"